// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ComponentList: typeof import('./components/ComponentList.vue')['default']
    CText: typeof import('./components/canvas/CText.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
  }
}

export { }
